# Generated by Django 6.1.1 on 2026-09-14 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionDetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('webcam_live', 'Live Webcam Stream'), ('webcam_snap', 'Webcam Snapshot'), ('image_upload', 'Image File Upload')], default='image_upload', max_length=20)),
                ('model_name', models.CharField(default='best_finetuned.keras', max_length=64)),
                ('primary_emotion', models.CharField(choices=[('Angry', 'Angry'), ('Fear', 'Fear'), ('Happy', 'Happy'), ('Sad', 'Sad'), ('Suprise', 'Suprise')], db_index=True, max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score between 0.0 and 1.0')),
                ('probabilities', models.JSONField(default=dict, help_text='Dict of emotion to confidence')),
                ('bounding_box', models.JSONField(blank=True, default=list, help_text='[x, y, w, h]')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/')),
                ('face_crop', models.ImageField(blank=True, null=True, upload_to='faces/%Y/%m/%d/')),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('face_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Emotion Detection Record',
                'verbose_name_plural': 'Emotion Detection Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
